#ifndef TESTCREATOR_SEMANTICVALIDATION_SEMANTICVALIDATOR_H
#define TESTCREATOR_SEMANTICVALIDATION_SEMANTICVALIDATOR_H

class SemanticValidator {
  // TODO: THIS
};

#endif /* TESTCREATOR_SEMANTICVALIDATION_SEMANTICVALIDATOR_H */
