#ifndef TESTCREATOR_STRUCTS_GENERALSETTINGSDESCRIPTOR_H
#define TESTCREATOR_STRUCTS_GENERALSETTINGSDESCRIPTOR_H

typedef std::map<std::string, std::string> GeneralSettingDescriptor;

#endif /* TESTCREATOR_STRUCTS_GENERALSETTINGSDESCRIPTOR_H */
